//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cobra.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int Id { get; set; }
        public int PhoneTypeId { get; set; }
        public int ProfileId { get; set; }
        public string Number { get; set; }
        public bool IsMobile { get; set; }
        public Nullable<int> CountryId { get; set; }
        public bool IsPrimary { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual PhoneType PhoneType { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
