//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cobra.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert
    {
        public int Id { get; set; }
        public int AlertTypeId { get; set; }
        public int PersonId { get; set; }
        public System.DateTime AlertStartTime { get; set; }
        public System.DateTime AlertEndTime { get; set; }
        public int CreatedBy { get; set; }
        public int Duration { get; set; }
    
        public virtual AlertType AlertType { get; set; }
        public virtual Person Person { get; set; }
    }
}
