//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cobra.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMedia
    {
        public int Id { get; set; }
        public int ProfileId { get; set; }
        public int SocialMediaTypeId { get; set; }
        public string AuthenticationToken { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual SocialMediaType SocialMediaType { get; set; }
    }
}
