//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataDrivenWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<double> Rate { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
