//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cobra.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public int Id { get; set; }
        public int EventTypeId { get; set; }
        public int PersonId { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime EventLoggedStarted { get; set; }
        public int EventLoggedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> EventLoggedEnd { get; set; }
        public Nullable<int> Duration { get; set; }
    
        public virtual EventType EventType { get; set; }
        public virtual Person Person { get; set; }
    }
}
